- backend/.env.example
- backend/.gitignore
- backend/app/config/config.js
- backend/app/middlewares/index.js
- backend/app/models/index.js
- backend/package-lock.json
- backend/package.json
- backend/server.js
#21 Initial project setup of Node.js
- Initial project setup with database MySQL.
- Created base folder for the route, service, and repository design pattern.
> #21 Initial project setup of Node.js

- backend/app/models/attachment.model.js
- backend/app/models/candidate.model.js
- backend/app/models/employer.model.js
#18 created attachment, candidate, employer model
> #18 created attachment, candidate, employer model

- backend/app/models/attachment.model.js
- backend/app/models/candidate.model.js
- backend/app/models/employer.model.js
- backend/app/models/index.js
- backend/app/models/job_application.model.js
- backend/app/models/job_application_education.model.js
- backend/app/models/job_application_experience.model.js
#18 created job applications models
> #18 created job applications models

- backend/app/models/job.model.js
- backend/app/models/user.model.js
> #18 Added job and user model

- backend/app/controllers/auth.controller.js
- backend/app/controllers/user.controller.js
- backend/app/middlewares/auth.js
- backend/app/middlewares/index.js
- backend/app/routes/auth.routes.js
- backend/app/routes/user.routes.js
#27 #11  Committed the following changes:
- Added middleware for JWT authentication
- Added Login endpoint with roles
- Added Sign Up endpoint
> #27 #11 Added login/signup endpoints

- backend/app/controllers/candidate.controller.js
- backend/app/routes/candidate.routes.js
> #31 Added candidate API

- backend/app/controllers/auth.controller.js
> #27 Removed role based login

- backend/app/routes/auth.routes.js
- backend/server.js
> #27 Fixed route issue

- backend/app/controllers/mail.controller.js
- backend/package-lock.json
- backend/package.json
> 41 email nodemailer setup

- backend/app/controllers/job_application.controller.js
- backend/app/models/index.js
- backend/app/routes/job_application.routes.js
- backend/server.js
#36 Created job application APIs
> #36 Created job application APIs

- backend/app/controllers/candidate.controller.js
- backend/app/controllers/employer.controller.js
- backend/app/routes/employer.routes.js
- backend/server.js
#46 Created employer profile creation API
> #46 Created employer profile creation API

- backend/app/controllers/candidate.controller.js
- backend/app/controllers/employer.controller.js
- backend/app/models/index.js
- backend/app/routes/candidate.routes.js
- backend/app/routes/employer.routes.js
#51 Added Get candidate and employer API
> #51 Added Get candidate and employer API

- backend/app/controllers/candidate.controller.js
- backend/app/controllers/jobs.controller.js
- backend/app/models/index.js
> #57 Modified job list API

- backend/app/controllers/job_application.controller.js
- backend/app/routes/job_application.routes.js
#59 Added job application status change api
> #59 Added job application status change api

- backend/app/controllers/jobs.controller.js
- backend/app/routes/job_application.routes.js
- backend/app/routes/jobs.routes.js
#61 Fixed method not supported error in jobs API
> #61 Fixed method not supported error in jobs API

- backend/app/controllers/jobs.controller.js
#66 Added user object in job list API
> #66 Added user object in job list API

- .github/workflows/build.yaml
> Removed test

- package.json
from no test to jest to check the working of CI/CD pipeline
> Updated test parameter

- .github/workflows/build.yaml
Build and deploypipeline. No frontend and backend deployment added yet
> Build and Deploy pipeline

- package.json
> Resolving error

- package.json
> Added devDependencies

- .gitignore
- backend/.gitignore
- backend/app/controllers/job_application.controller.js
- backend/app/routes/job_application.routes.js
- backend/package-lock.json
- backend/package.json
#93 Auto resume creation + created API to fetch last education and experience details
> Auto resume creation + created API to fetch last education and experience details

- backend/app/controllers/user.controller.js
> #68 APIs for ADMIN

- .github/workflows/build.yaml
- backend/server.js
- ui/career-platform-factory.js
#74 
- Build
- Install the dependencies for the backend and frontend
- Run the test cases 
- Deploy
- Deploy the backend and frontend 
- Instal ngrok to access the application from outside of the Ubuntu cluster
> Created GitHub Action Workflow file #74
